apiVersion: v2
publisher: telemetry-plugin-publisher
name: little-telemetry-backend
version: 0.0.1
type: Che Plugin
displayName: Little Telemetry Backend
description: A Demo telemetry backend
title: Little Telemetry Backend
category: Other
spec:
  workspaceEnv:
    - name: CHE_WORKSPACE_TELEMETRY_BACKEND_PORT
      value: '4167'
  containers:
  - name: itstelemetrycontainer
    image: docker.io/andrazeez/telemetry-plugin-test:v6
    env:
      - name: CHE_API
        value: $(CHE_API_INTERNAL)
