apiVersion: v2
publisher: telemetry-plugin-publisher
name: little-telemetry-backend
version: 0.0.1
type: Che Plugin
displayName: Little Telemetry Backend
description: A Demo telemetry backend
title: Little Telemetry Backend
category: Other
spec:
  workspaceEnv:
    - name: CHE_WORKSPACE_TELEMETRY_BACKEND_PORT
      value: '4167'
  containers:
  - name: itstelemetrycontainer
    image: docker.io/andrazeez/telemetry-plugin-test:v10
    #image: docker.io/andrazeez/jvmtelemetry-plugin-test:v1
    env:
      - name: CHE_API
        value: $(CHE_API_INTERNAL)
      - name: EDX_BASE_URL
        value: "https://learn-dev.springpeople.com/oauth2/access_token"
      - name: EDX_CLIENT_SECRET
        value: "4uU5hi11xV8h4R4EURNuVAHA32Zg2GwqxPaZfhPf93u2rJgRFCV9K8YxlWr8FC1TrOlrUQlDceszsR2ghPjoF1z9JxBZesJjhUnJ87dItb1gbNFWXLlqZu65TbxFBfpA"
      - name: EDX_CLIENT_ID
        value: "login-api"
